DROP TABLE IF EXISTS zambiaCensus2010rec2;

CREATE TEMPORARY TABLE _temp (
prov varchar (2),
dist varchar (4),
const varchar (3),
ward varchar (2),
region varchar (1),
csa varchar (2),
sea varchar (1),
cbn varchar (4),
hun varchar (3),
hhn varchar (2),
pid varchar (4),
p1_line_number varchar (1),
p2_membership varchar (1),
p3_rel varchar (2),
p4_sex varchar (1),
p5_age varchar (2),
p6_pob varchar (3),
p7_region_at_birth varchar (1),
p8_zambian varchar (1),
p9_country varchar (3),
p10_purpose varchar (1),
p11_religion varchar (1),
p12_ethnicity varchar (2),
p13_language varchar (2),
p14_prev_res varchar (3),
p15a_same_as_head varchar (1),
p15b_living_cont_years varchar (2),
p15c_living_cont_months varchar (2),
p16_disability varchar (1),
p17_type_blind varchar (2),
p17_type_partially_sighted varchar (2),
p17_type_deaf_dumb varchar (2),
p17_type_deaf varchar (2),
p17_type_hard_of_hearing varchar (2),
p17_type_dumb varchar (2),
p17_type_mental_illness varchar (2),
p17_type_intellectual varchar (2),
p17_type_speech varchar (2),
p17_type_physically varchar (2),
p17_type_mentally_retarded varchar (2),
p17_type_others varchar (2),
p18_cause_congenital varchar (1),
p18_cause_disease varchar (1),
p18_cause_injury varchar (1),
p18_cause_spousal varchar (1),
p18_cause_other_violence varchar (1),
p18_cause_unknown varchar (1),
p18_cause_other varchar (1),
p19_albino varchar (1),
p20_mother_alive varchar (1),
p21_mother_in_hh varchar (1),
p22_father_alive varchar (1),
p23_father_in_hh varchar (1),
p24_birth_cert varchar (1),
p25_read_write varchar (1),
p26_ever_attend_school varchar (1),
p27_attending_school varchar (1),
p28_highest_level varchar (2),
p29_high_vocation varchar (1),
p30_field_of_study varchar (2),
p31_activity_last_7_days varchar (2),
p32_activity_last_12_months varchar (2),
p33_employment_status varchar (1),
p34_occupation varchar (3),
p35_industry varchar (3),
p36_marital_status varchar (1),
p37_age_first_marraige varchar (2),
p38_live_birth varchar (1),
p39m_male_live_in_hh varchar (2),
p39f_female_live_in_hh varchar (2),
p40m_males_elsewhere varchar (2),
p40f_females_elsewhere varchar (2),
p41m_males_died varchar (2),
p41f_females_died varchar (2),
p42_last_12_mon varchar (1),
p43m_past_yr_in_hh varchar (2),
p43f_past_yr_in_hh varchar (2),
p44m_past_yr_elsewhere varchar (2),
p44f_past_yr_elsewhere varchar (2),
p45m_past_year_died varchar (2),
p45f_past_year_died varchar (2),
p46_registration varchar (1),
p47_voter varchar (1),
pop_barcode varchar (10),
males_ceb varchar (2),
females_ceb varchar (2),
ceb_total varchar (2),
ceb_with_you_total varchar (2),
ceb_elsewhere_total varchar (2),
ceb_dead_total varchar (2),
ceb_males_surviving varchar (2),
ceb_females_surviving varchar (2),
ceb_total_surviving varchar (2),
total_male_births_12months varchar (2),
total_female_births_12months varchar (2),
total_births_12months varchar (2),
births_12months_surviving_malet varchar (2),
births_12months_surviving_femalf varchar (2),
total_births_12months_survivinh varchar (2),
total_births_12_months_dead varchar (2),
p17a_type_blind varchar (1),
p17b_type_partially_sighted varchar (1),
p17c_type_deaf_dumb varchar (1),
d17d_type_deaf varchar (1),
p17e_type_hard_of_hearing varchar (1),
p17f_type_dumb varchar (1),
p17g_type_mental_illness varchar (1),
p17h_type_intellectual varchar (1),
p17i_type_speech varchar (1),
p17j_type_physically varchar (1),
p17k_type_mentally_retarded varchar (1),
p17l_type_other_disability varchar (1),
p18a_cause_congenital varchar (1),
p18b_cause_disease varchar (1),
p18c_cause_injury varchar (1),
p18d_cause_spousal varchar (1),
p18e_cause_other_violence varchar (1),
p18f_cause_unknown varchar (1),
p18g_cause_other varchar (1),
pob_recoded varchar (4),
country_recoded varchar (4),
recoded_residence varchar (4),
household_size varchar (3),
cgi varchar (1),
oi varchar (1),
ei varchar (1),
di varchar (1),
fit varchar (1),
unfit varchar (1),
nullrec varchar (1));

copy _temp from '/home/ram22/dataDrive/dataProjects/povMap/zambiaLFSmapping/2_data/zambiaCensus2010rec2.txt' (delimiter '|');

ALTER TABLE _temp
DROP nullrec;

CREATE TABLE zambiaCensus2010rec2 as
SELECT 
cast(nullif(prov , '') as smallint) as prov ,
cast(nullif(dist , '') as smallint) as dist ,
cast(nullif(const , '') as smallint) as const ,
cast(nullif(ward , '') as smallint) as ward ,
cast(nullif(region , '') as smallint) as region ,
cast(nullif(csa , '') as smallint) as csa ,
cast(nullif(sea , '') as smallint) as sea ,
cast(nullif(cbn , '') as smallint) as cbn ,
cast(nullif(hun , '') as smallint) as hun ,
hhn,
cast(nullif(pid , '') as smallint) as pid ,
cast(nullif(p1_line_number , '') as smallint) as p1_line_number ,
cast(nullif(p2_membership , '') as smallint) as p2_membership ,
cast(nullif(p3_rel , '') as smallint) as p3_rel ,
cast(nullif(p4_sex , '') as smallint) as p4_sex ,
cast(nullif(p5_age , '') as smallint) as p5_age ,
p6_pob,
cast(nullif(p7_region_at_birth , '') as smallint) as p7_region_at_birth ,
cast(nullif(p8_zambian , '') as smallint) as p8_zambian ,
p9_country,
cast(nullif(p10_purpose , '') as smallint) as p10_purpose ,
cast(nullif(p11_religion , '') as smallint) as p11_religion ,
cast(nullif(p12_ethnicity , '') as smallint) as p12_ethnicity ,
cast(nullif(p13_language , '') as smallint) as p13_language ,
p14_prev_res,
cast(nullif(p15a_same_as_head , '') as smallint) as p15a_same_as_head ,
cast(nullif(p15b_living_cont_years , '') as smallint) as p15b_living_cont_years ,
cast(nullif(p15c_living_cont_months , '') as smallint) as p15c_living_cont_months ,
cast(nullif(p16_disability , '') as smallint) as p16_disability ,
cast(nullif(p17_type_blind , '') as smallint) as p17_type_blind ,
cast(nullif(p17_type_partially_sighted , '') as smallint) as p17_type_partially_sighted ,
cast(nullif(p17_type_deaf_dumb , '') as smallint) as p17_type_deaf_dumb ,
cast(nullif(p17_type_deaf , '') as smallint) as p17_type_deaf ,
cast(nullif(p17_type_hard_of_hearing , '') as smallint) as p17_type_hard_of_hearing ,
cast(nullif(p17_type_dumb , '') as smallint) as p17_type_dumb ,
cast(nullif(p17_type_mental_illness , '') as smallint) as p17_type_mental_illness ,
cast(nullif(p17_type_intellectual , '') as smallint) as p17_type_intellectual ,
cast(nullif(p17_type_speech , '') as smallint) as p17_type_speech ,
cast(nullif(p17_type_physically , '') as smallint) as p17_type_physically ,
cast(nullif(p17_type_mentally_retarded , '') as smallint) as p17_type_mentally_retarded ,
cast(nullif(p17_type_others , '') as smallint) as p17_type_others ,
cast(nullif(p18_cause_congenital , '') as smallint) as p18_cause_congenital ,
cast(nullif(p18_cause_disease , '') as smallint) as p18_cause_disease ,
cast(nullif(p18_cause_injury , '') as smallint) as p18_cause_injury ,
cast(nullif(p18_cause_spousal , '') as smallint) as p18_cause_spousal ,
cast(nullif(p18_cause_other_violence , '') as smallint) as p18_cause_other_violence ,
cast(nullif(p18_cause_unknown , '') as smallint) as p18_cause_unknown ,
cast(nullif(p18_cause_other , '') as smallint) as p18_cause_other ,
cast(nullif(p19_albino , '') as smallint) as p19_albino ,
cast(nullif(p20_mother_alive , '') as smallint) as p20_mother_alive ,
cast(nullif(p21_mother_in_hh , '') as smallint) as p21_mother_in_hh ,
cast(nullif(p22_father_alive , '') as smallint) as p22_father_alive ,
cast(nullif(p23_father_in_hh , '') as smallint) as p23_father_in_hh ,
cast(nullif(p24_birth_cert , '') as smallint) as p24_birth_cert ,
cast(nullif(p25_read_write , '') as smallint) as p25_read_write ,
cast(nullif(p26_ever_attend_school , '') as smallint) as p26_ever_attend_school ,
cast(nullif(p27_attending_school , '') as smallint) as p27_attending_school ,
cast(nullif(p28_highest_level , '') as smallint) as p28_highest_level ,
cast(nullif(p29_high_vocation , '') as smallint) as p29_high_vocation ,
cast(nullif(p30_field_of_study , '') as smallint) as p30_field_of_study ,
cast(nullif(p31_activity_last_7_days , '') as smallint) as p31_activity_last_7_days ,
cast(nullif(p32_activity_last_12_months , '') as smallint) as p32_activity_last_12_months ,
cast(nullif(p33_employment_status , '') as smallint) as p33_employment_status ,
cast(nullif(p34_occupation , '') as smallint) as p34_occupation ,
cast(nullif(p35_industry , '') as smallint) as p35_industry ,
cast(nullif(p36_marital_status , '') as smallint) as p36_marital_status ,
cast(nullif(p37_age_first_marraige , '') as smallint) as p37_age_first_marraige ,
cast(nullif(p38_live_birth , '') as smallint) as p38_live_birth ,
cast(nullif(p39m_male_live_in_hh , '') as smallint) as p39m_male_live_in_hh ,
cast(nullif(p39f_female_live_in_hh , '') as smallint) as p39f_female_live_in_hh ,
cast(nullif(p40m_males_elsewhere , '') as smallint) as p40m_males_elsewhere ,
cast(nullif(p40f_females_elsewhere , '') as smallint) as p40f_females_elsewhere ,
cast(nullif(p41m_males_died , '') as smallint) as p41m_males_died ,
cast(nullif(p41f_females_died , '') as smallint) as p41f_females_died ,
cast(nullif(p42_last_12_mon , '') as smallint) as p42_last_12_mon ,
cast(nullif(p43m_past_yr_in_hh , '') as smallint) as p43m_past_yr_in_hh ,
cast(nullif(p43f_past_yr_in_hh , '') as smallint) as p43f_past_yr_in_hh ,
cast(nullif(p44m_past_yr_elsewhere , '') as smallint) as p44m_past_yr_elsewhere ,
cast(nullif(p44f_past_yr_elsewhere , '') as smallint) as p44f_past_yr_elsewhere ,
cast(nullif(p45m_past_year_died , '') as smallint) as p45m_past_year_died ,
cast(nullif(p45f_past_year_died , '') as smallint) as p45f_past_year_died ,
cast(nullif(p46_registration , '') as smallint) as p46_registration ,
cast(nullif(p47_voter , '') as smallint) as p47_voter ,
pop_barcode,
cast(nullif(males_ceb , '') as smallint) as males_ceb ,
cast(nullif(females_ceb , '') as smallint) as females_ceb ,
cast(nullif(ceb_total , '') as smallint) as ceb_total ,
cast(nullif(ceb_with_you_total , '') as smallint) as ceb_with_you_total ,
cast(nullif(ceb_elsewhere_total , '') as smallint) as ceb_elsewhere_total ,
cast(nullif(ceb_dead_total , '') as smallint) as ceb_dead_total ,
cast(nullif(ceb_males_surviving , '') as smallint) as ceb_males_surviving ,
cast(nullif(ceb_females_surviving , '') as smallint) as ceb_females_surviving ,
cast(nullif(ceb_total_surviving , '') as smallint) as ceb_total_surviving ,
cast(nullif(total_male_births_12months , '') as smallint) as total_male_births_12months ,
cast(nullif(total_female_births_12months , '') as smallint) as total_female_births_12months ,
cast(nullif(total_births_12months , '') as smallint) as total_births_12months ,
cast(nullif(births_12months_surviving_malet , '') as smallint) as births_12months_surviving_malet ,
cast(nullif(births_12months_surviving_femalf , '') as smallint) as births_12months_surviving_femalf ,
cast(nullif(total_births_12months_survivinh , '') as smallint) as total_births_12months_survivinh ,
cast(nullif(total_births_12_months_dead , '') as smallint) as total_births_12_months_dead ,
cast(nullif(p17a_type_blind , '') as smallint) as p17a_type_blind ,
cast(nullif(p17b_type_partially_sighted , '') as smallint) as p17b_type_partially_sighted ,
cast(nullif(p17c_type_deaf_dumb , '') as smallint) as p17c_type_deaf_dumb ,
cast(nullif(d17d_type_deaf , '') as smallint) as d17d_type_deaf ,
cast(nullif(p17e_type_hard_of_hearing , '') as smallint) as p17e_type_hard_of_hearing ,
cast(nullif(p17f_type_dumb , '') as smallint) as p17f_type_dumb ,
cast(nullif(p17g_type_mental_illness , '') as smallint) as p17g_type_mental_illness ,
cast(nullif(p17h_type_intellectual , '') as smallint) as p17h_type_intellectual ,
cast(nullif(p17i_type_speech , '') as smallint) as p17i_type_speech ,
cast(nullif(p17j_type_physically , '') as smallint) as p17j_type_physically ,
cast(nullif(p17k_type_mentally_retarded , '') as smallint) as p17k_type_mentally_retarded ,
cast(nullif(p17l_type_other_disability , '') as smallint) as p17l_type_other_disability ,
cast(nullif(p18a_cause_congenital , '') as smallint) as p18a_cause_congenital ,
cast(nullif(p18b_cause_disease , '') as smallint) as p18b_cause_disease ,
cast(nullif(p18c_cause_injury , '') as smallint) as p18c_cause_injury ,
cast(nullif(p18d_cause_spousal , '') as smallint) as p18d_cause_spousal ,
cast(nullif(p18e_cause_other_violence , '') as smallint) as p18e_cause_other_violence ,
cast(nullif(p18f_cause_unknown , '') as smallint) as p18f_cause_unknown ,
cast(nullif(p18g_cause_other , '') as smallint) as p18g_cause_other ,
cast(nullif(pob_recoded , '') as smallint) as pob_recoded ,
cast(nullif(country_recoded , '') as smallint) as country_recoded ,
cast(nullif(recoded_residence , '') as smallint) as recoded_residence ,
cast(nullif(household_size , '') as smallint) as household_size ,
cast(nullif(cgi , '') as smallint) as cgi ,
cast(nullif(oi , '') as smallint) as oi ,
cast(nullif(ei , '') as smallint) as ei ,
cast(nullif(di , '') as smallint) as di ,
cast(nullif(fit , '') as smallint) as fit ,
cast(nullif(unfit , '') as smallint) as unfit
from _temp;

drop table _temp;

